_wandb:
    value:
        cli_version: 0.22.2
        e:
            hnev8ya9h8mg5hhpblv93g4f7cm4d2m6:
                args:
                    - fit
                    - --config
                    - config.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982240026624"
                        used: "175836106752"
                email: hoonwin02@seoultech.ac.kr
                executable: /home/mixlab/tabular/ecganalysisapp2/miniconda3/envs/cxr13/bin/python
                git:
                    commit: f7d2829c0aab403fbd21dcf4948be0a41a528973
                    remote: https://github.com/shchooii/CheXFusion.git
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-afb618da-2c9d-56bb-5bde-86a589f13211
                host: ssh-csh-deployment-5fc7d8654b-qzlj9
                memory:
                    total: "270058926080"
                os: Linux-5.15.0-151-generic-x86_64-with-glibc2.35
                program: /home/mixlab/tabular/shchoi/CheXFusion/main.py
                python: CPython 3.10.19
                root: .
                startedAt: "2025-10-20T07:42:07.257097Z"
                writerId: hnev8ya9h8mg5hhpblv93g4f7cm4d2m6
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 80
                - 106
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 80
                - 106
            "3":
                - 7
                - 13
                - 15
                - 66
            "4": 3.10.19
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
loss_init_args:
    value:
        class_instance_nums:
            - 67597
            - 4361
            - 76900
            - 16038
            - 38574
            - 4255
            - 30119
            - 1158
            - 11883
            - 4049
            - 10218
            - 2533
            - 79931
            - 5529
            - 41869
            - 7663
            - 69240
            - 675
            - 3369
            - 788
            - 48093
            - 543
            - 14983
            - 2453
            - 89140
            - 3499
        total_instance_num: 264849
        type: asl
lr:
    value: 3e-05
timm_init_args:
    value:
        model_name: convnext_small.fb_in22k_ft_in1k
        num_classes: 26
        pretrained: true
