_wandb:
    value:
        cli_version: 0.22.2
        e:
            dmos8ma7sgad9vabu1an8wcf3j73xpwo:
                args:
                    - fit
                    - --config
                    - config.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982240026624"
                        used: "169721741312"
                email: hoonwin02@seoultech.ac.kr
                executable: /home/mixlab/tabular/ecganalysisapp2/miniconda3/envs/cxr2/bin/python
                git:
                    commit: f7d2829c0aab403fbd21dcf4948be0a41a528973
                    remote: https://github.com/shchooii/CheXFusion.git
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-afb618da-2c9d-56bb-5bde-86a589f13211
                host: ssh-csh-deployment-5fc7d8654b-qzlj9
                memory:
                    total: "270058926080"
                os: Linux-5.15.0-151-generic-x86_64-with-glibc2.35
                program: /home/mixlab/tabular/shchoi/CheXFusion/main.py
                python: CPython 3.10.19
                root: .
                startedAt: "2025-10-20T06:30:23.578913Z"
                writerId: dmos8ma7sgad9vabu1an8wcf3j73xpwo
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 80
                - 106
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 80
                - 106
            "3":
                - 7
                - 13
                - 15
                - 66
            "4": 3.10.19
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
